name: A new issue activity happened
on: issues
jobs:
  print-issue-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue details
        run: echo "Issue details ${{ toJSON(github.event) }}"